![numpy.png](numpy.png)

## Creation of array

In [51]:
my_list = [1,2,3,4,5,6]
print(my_list)

[1, 2, 3, 4, 5, 6]


## To create numpy array we import the numpy package

In [52]:
import numpy as np

In [53]:
array = np.array(my_list,dtype= int)

In [54]:
print(type(array))
print(len(array))
print(array.ndim)
print(array.shape)

<class 'numpy.ndarray'>
6
1
(6,)


In [55]:
array2 = array.reshape(3,2)
print(array2)
array2.shape

[[1 2]
 [3 4]
 [5 6]]


(3, 2)

In [56]:
array3 = array.reshape(3,-1)     # -1 to calculate column automatically


In [57]:
##Intializing numpy arrays from nested Python lists

my_list2 = [1,2,3,4,5]
my_list3 = [6,7,8,9,0]
my_list4 = [0,1,0,1,0]

arr_3d  = np.array([my_list2,my_list3,my_list4])
print(arr_3d)
print(arr_3d.shape)

[[1 2 3 4 5]
 [6 7 8 9 0]
 [0 1 0 1 0]]
(3, 5)


In [58]:
arr_3d.reshape(1,15)

array([[1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 0, 1, 0, 1, 0]])

## NumPy-Attributes

In [59]:
a = np.array([[1,2,3],[4,5,6]])
print(a.shape)

(2, 3)


In [60]:
#reshaping the ndarray
a.shape = (3,2)
print(a)

[[1 2]
 [3 4]
 [5 6]]


In [61]:
#reshape function to resize an arrray
b = a.reshape(2,3)
print(b)

[[1 2 3]
 [4 5 6]]


In [62]:
r = range(24)

In [63]:
print(r)

range(0, 24)


In [64]:
# an array of evenly spaced numbers
a=np.arange(24)
print(a)
print(a.ndim)


[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
1


In [65]:
# Reshaping the array a
b = a.reshape(6,2,2)  # .reshape(vector,row,column)
print(b)

[[[ 0  1]
  [ 2  3]]

 [[ 4  5]
  [ 6  7]]

 [[ 8  9]
  [10 11]]

 [[12 13]
  [14 15]]

 [[16 17]
  [18 19]]

 [[20 21]
  [22 23]]]


### numpy.itemsize
the array attribute returns the length of each element of array in bytes

In [66]:
# dtype of array is int8 1 byte
x = np.array([1,2,4,5,6],dtype=np.int8)
print(x.itemsize)

1


In [67]:
# dtype of array is float32 4 byte
x = np.array([1,2,4,5,6],dtype=np.float32)
print(x.itemsize)

4


## NumPy Arithmetic Operations

In [68]:
x = np.array([[1,2],[3,4]],dtype=np.float64)
y = np.array([[5,6],[7,8]],dtype=np.float64)
print(x)
print(y)

[[1. 2.]
 [3. 4.]]
[[5. 6.]
 [7. 8.]]


In [69]:
print(x+y)
print(np.add(x,y))

[[ 6.  8.]
 [10. 12.]]
[[ 6.  8.]
 [10. 12.]]


In [70]:
print(x-y)
print(np.subtract(x,y))

[[-4. -4.]
 [-4. -4.]]
[[-4. -4.]
 [-4. -4.]]


In [71]:
print(x*y)
print(np.multiply(x,y))
print(x.dot(y))
print(np.dot(x,y))

[[ 5. 12.]
 [21. 32.]]
[[ 5. 12.]
 [21. 32.]]
[[19. 22.]
 [43. 50.]]
[[19. 22.]
 [43. 50.]]


In [72]:
print(x/y)
print(np.divide(x,y))


[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [73]:
print(np.sum(x))                  # Compute sum of all elements
print(np.sum(x, axis=0))          # Compute sum of each column
print(np.sum(x, axis=1))          # Compute sum of each row

10.0
[4. 6.]
[3. 7.]
